//Import required libraries
var path = require('path');
var express = require('express');
var app = express();

//Let Node.js Express know where we have the HTML page.
var htmlPath = path.join(__dirname, 'html');
app.use(express.static(htmlPath));

//Start the server and listen for requests on port 3000.
var server = app.listen(3000, function () {
    var host = 'localhost';
    var port = server.address().port;
    console.log('listening on http://'+host+':'+port+'/');
});

//GET score request entry point, example http://localhost:3000/score?name=image.jpg
app.get('/score',function(req,res){
	var imageName = req.query.name;
	var score = calculateImageScore(imageName);
	console.log("Calculated score for "+imageName+" - "+score+"!");
	res.send(score.toString());
})

//Converts the image name to a hashcode and calculates a score between 1-10 using sin.
function calculateImageScore(imageName){
	var hash = hashCode(imageName);
	return Math.abs(Math.floor(Math.sin(hash) * 10));
}

//Converts a string to an integer value, generated by a hashing algorithm.
function hashCode(s) {
    for(var i = 0, h = 0; i < s.length; i++)
        h = Math.imul(31, h) + s.charCodeAt(i) | 0;
    return h;
}

module.exports = app; // Expose the app for testing